tempo = 4  # /4
first_note = " d'"  # min "c,,," max "c'''''"
bar_count = 4  # num. of bars
lowest_note = " c'"  # min "c,,," max "c'''''"
highest_note = " e'"  # min "c,,," max "c'''''"
rest_prob = 0  # number between 0 and 1

# interval probabilities, enter natural numbers incl. 0
unison_prob = 1
diminished_second_prob = 1
augmented_unison_prob = 1
minor_second_prob = 1
major_second_prob = 1
diminished_third_prob = 1
augmented_second_prob = 1
minor_third_prob = 1
major_third_prob = 1
diminished_fourth_prob = 1
augmented_third_prob = 1
fourth_prob = 1
augmented_fourth_prob = 1
diminished_fifth_prob = 1
fifth_prob = 1
diminished_sixth_prob = 1
augmented_fifth_prob = 1
minor_sixth_prob = 1
major_sixth_prob = 1
diminished_seventh_prob = 1
augmented_sixth_prob = 1
minor_seventh_prob = 1
major_seventh_prob = 1
diminished_octave_prob = 1
augmented_seventh_prob = 1
octave_prob = 1

# pitch probabilities, enter natural numbers incl. 0
c_prob = 1
cis_prob = 1
d_prob = 1
dis_prob = 1
e_prob = 1
eis_prob = 1
f_prob = 1
fis_prob = 1
g_prob = 1
gis_prob = 1
a_prob = 1
ais_prob = 1
b_prob = 1
bis_prob = 1
